SinadjanRudge/doct

app/src/main/AndroidManifest.xml, build-app/output-metadata.json
Deleted intent-filter from main activity in android manifest
=> Item installs 2 apps when using physical device

.idea/gradle.xml, .idea/kotlinScripting.xml, app/src/main/java/com/triadss/doctrack2/activity/LoginActivity.java
- Fix a bug that will close after login, just removed the finish() function inside mAuth's signInWithEmailAndPassword function.
=> Bug: App close after login

app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/AddPatientFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/AppointmentPending.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/AppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/config/constants/AppointmentTypeConstants.java, app/src/main/java/com/triadss/doctrack2/config/constants/FireStoreCollection.java, app/src/main/java/com/triadss/doctrack2/config/model/AppointmentsModel.java, app/src/main/java/com/triadss/doctrack2/config/model/MedicationModel.java, app/src/main/java/com/triadss/doctrack2/config/model/VitalSignsModel.java, app/src/main/java/com/triadss/doctrack2/config/model/WearableDeviceModel.java, app/src/main/java/com/triadss/doctrack2/dto/AppointmentDto.java, app/src/main/java/com/triadss/doctrack2/dto/MedicationDto.java, app/src/main/java/com/triadss/doctrack2/dto/VitalSignsDto.java, app/src/main/java/com/triadss/doctrack2/dto/WearableDeviceDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/MedicationRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/PatientRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/VitalSignsRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/WearableDeviceRepository.java, app/src/main/res/layout/activity_patient_request.xml
**In AppointmentDto.java (/dto):**
- added createdAt (Timestamp), as well as it's getters and setters
- added patientId (String), as well as it's getters and setters
- removed timeAppointment (long) variable, moved it's values to the dateOfAppointment (Timestamp - date with time)
- added a default constructor
- added a constructor that passes all its values
**In AppointmentRepository.java (/repository):**
- added addAppointment() function for adding an appointment
- added getAllAppointments() which will fetch all the appointments in descending order via createdAt field
- added AppointmentAddCallback and AppointmentFetchCallback
**In ApppointmentRequest.java (/fragment):**
- refactored the code, move all the button, date, and edit text setters into functions
- can get all the values of the …
=> Item Patient's Appointments' Add and Get Appointments

app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/AppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java
**In AppointmentRepository.java:**
- modified getAllAppointments() function to include also the document id or the appointmentId when fetching the data.
- modified AppointmentFetchCallback's on onSuccess function
- added updateAppointment which will have a PATCH behavior when updating a data to avoid setting nulls in the document's fields.
- added getAppointment() function where it will fetch one appointment using the appointmentId or document id **(must exist in the firestore)**
- added deleteAppointment() function where it will delete a one appointment using the appointmentId
- added interface callbacks such as AppointmentFetchOneCallback, UpdateAppointmentCallback, and DeleteAppointmentCallback
**In AppointmentRequest.java:**
- added all the testing values, and I commented it. I think …
=> Item Patient Appointments Repository Backend Functions

app/src/main/java/com/triadss/doctrack2/activity/patient/PatientHome.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientMedicationAddFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientMedicationCompletedFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientMedicationFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientMedicationFragmentPageAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientMedicationOngoingFragment.java, app/src/main/java/com/triadss/doctrack2/dto/DateDto.java, app/src/main/java/com/triadss/doctrack2/dto/DateTimeDto.java, app/src/main/java/com/triadss/doctrack2/dto/MedicationDto.java, app/src/main/java/com/triadss/doctrack2/dto/TimeDto.java, app/src/main/res/layout/fragment_patient_medication.xml, app/src/main/res/layout/fragment_patient_medication_add.xml, app/src/main/res/layout/fragment_patient_medication_completed.xml, app/src/main/res/layout/fragment_patient_medication_ongoing.xml
Re organized Add Medication layout.
Created DateDto and TimeDto 
Created Medication Top Navigation
=> Patient Add Medication Front End update

app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/AppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientMedicationAddFragment.java, app/src/main/java/com/triadss/doctrack2/config/constants/FireStoreCollection.java, app/src/main/java/com/triadss/doctrack2/dto/MedicationDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/MedicationRepository.java, app/src/main/res/layout/fragment_patient_medication_add.xml
In the **PatientMedicationAddFragment.java**:
- changed the cancel to clear button that will clear the values of the variables.
- added setup functions in the fragment
- made the backend and the AddMedication fragment integrated by calling the addMedication in the fragment.
- rename some of the variable names in the fragment and also in the layout file.
In the **MedicationRepository.java**:
- added callbacks and error handlings for add medication
- added add medication
- made the mediId not included when adding medication in the db.
In the **MedicationDto.java**:
- modified the IDs type to String
=> Item_Patient-Add-Medication_Nico - Adding a Medication to the DB

app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/AppointmentPending.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/AppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/AppointmentStatus.java, app/src/main/java/com/triadss/doctrack2/dto/DateTimeDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java
Updated Timestamp to String presentation via DateTime Dtos
Some code cleanup
=> Fixed timestamp for Pending and Status pages

app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/PatientFragmentAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/PatientFragment.java, app/src/main/res/layout/list_healthprof_patient.xml
Modified PatientFragmentAdapter
-added OnItemClickListener
-modified PatientFragmentViewHolder class
Modified PatientFragment
-added showPatientRecord method
-set the listener
Note: Not sure for the fragment of View Record if existing already
=> View Patient Record

app/src/main/AndroidManifest.xml, app/src/main/java/com/triadss/doctrack2/activity/patient/PatientHome.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentFragmentPageAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentPending.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentStatus.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentStatusAdapter.java, app/src/main/res/layout/activity_patient_appointment.xml, app/src/main/res/layout/activity_patient_request.xml, app/src/main/res/layout/activity_patient_status.xml, app/src/main/res/layout/activity_pending.xml
Refactored code for using recyclerView to avoid code duplications
=> Refactored approach PatientAppointments Pending and Status

app/src/main/java/com/triadss/doctrack2/activity/healthprof/HealthProfessionalPending.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/HealthProfessionalUpcoming.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalAppointmentUpcomingAdapter.java
Fixed presentation of Timestamps
Refactored usage of multiple arraylist per property
Refactor view holder to contain its own update function
=> Fixed presentation of Upcoming and Pending Appointments

app/src/main/java/com/triadss/doctrack2/activity/patient/PatientHome.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentPendingAdapter.java, app/src/main/res/layout/fragment_patient_appointment_reschedule.xml, app/src/main/res/layout/fragment_update_record.xml, app/src/main/res/values/strings.xml
Pending Patient Appointment Cards open the Reschedule modal
=> Integrated Patient Appointment Reschedule Pending Modal

app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientMedicationOngoingAdapter.java, app/src/main/res/layout/dialog_update_medication.xml
Clicking update button on ongoing medication opens update modal.
=> Created Patient Medication Update Modal

app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalAppointmentPendingAdapter.java
Reschedule modal is opened when clicking Reschedule button for HealthProfessional's Pending Appointment.
Haven't tested yet but seems to work in theory.
=> Added reschedule modal for HealthProfessional Pending Appointment

app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/RecordMedication.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/RecordMedicationAdapter.java, app/src/main/res/layout/fragment_record_medication.xml, app/src/main/res/layout/list_item_medication_record.xml
Patient Records Medications shows list of medications
Haven't tested yet but in theory it should work
(Still waiting for Ongoing filter, so for now it shows all medications)
=> Patient Records Medications Update

app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/RecordMedication.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/RecordPersonalInfo.java, app/src/main/java/com/triadss/doctrack2/config/model/UserModel.java, app/src/main/res/layout/fragment_record_personal_info.xml
Patient Records Personal Information tab will update based on actual values from user
=> Patient Records Personal Information Update

app/src/main/java/com/triadss/doctrack2/activity/healthprof/HealthProfessionalPending.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/HealthProfessionalStatus.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/HealthProfessionalUpcoming.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalAppointmentFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalAppointmentStatusAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalAppointmentUpcomingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/config/model/AppointmentsModel.java, app/src/main/java/com/triadss/doctrack2/dto/AppointmentDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java, app/src/main/res/layout/dialog_cancel_appointment_confirmation.xml, app/src/main/res/layout/fragment_health_professional_pending.xml, app/src/main/res/layout/fragment_health_professional_status.xml, app/src/main/res/layout/fragment_health_professional_upcoming.xml
1. Status shows all Pending Appointment assigned to Health Prof or Ongoing Health Professionals
2. Rejecting Upcoming Pending will open Dialog then delete appointment once confirmed
3. Upcoming shows all Upcoming patient appointments
4. Accepting appointment will assign appointment to health prof then move to Pending page
5. Pending shows all Pending appointment assigned to health prof
6. Pending reschedule implemented
7. Pending cancel implemented
=> Completed Backend for Health Professional Appointments

app/src/main/java/com/triadss/doctrack2/activity/admin/AdminManageUserAccount.java, app/src/main/res/layout/fragment_admin_manage_user_account.xml
From Manage User Accounts, you can navigate to Add Health Professional Profile page
=> Navigation to Create Health Professional page

.idea/misc.xml, app/src/main/java/com/triadss/doctrack2/activity/admin/AdminGenerateReportsPage.java, app/src/main/java/com/triadss/doctrack2/activity/admin/EditAdminGenerateReportsCard.java, app/src/main/java/com/triadss/doctrack2/activity/admin/UpdateHealthProfPage.java, app/src/main/java/com/triadss/doctrack2/activity/admin/ViewHealthProfPage.java, app/src/main/res/layout/fragment_admin_generate_reports_page.xml, app/src/main/res/layout/fragment_create_health_professional_page.xml, app/src/main/res/layout/fragment_edit_admin_generate_reports_card.xml, app/src/main/res/layout/fragment_update_health_prof_page.xml, app/src/main/res/layout/fragment_view_health_prof_page.xml, app/src/main/res/values/strings.xml
Admin Generate Report Page
Edit Admin Generate Reports Card
Update Heath Prof Page
View Health Prof Page
3-16-2024
=> Item admin mange user account mary

.idea/misc.xml, app/src/main/java/com/triadss/doctrack2/CreateReportsPage.java, app/src/main/java/com/triadss/doctrack2/ReportsCard.java, app/src/main/res/layout/fragment_create_reports_page.xml, app/src/main/res/layout/fragment_reports_card.xml, app/src/main/res/layout/fragment_update_record.xml
Report Page
Report Card
-Mary
3-17-2024
5:30
=> Report Page

app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java
added reports to 
Cancel
Reschedule
=> Added reports 

app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/AddMedicalHistory.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/UpdateMedicalHistory.java, app/src/main/res/layout/fragment_patient_record_add_medical_history.xml, app/src/main/res/layout/fragment_update_medical_history.xml
restore deleted files
adding new checkboxes
=> Modified add and update medical history

app/src/main/res/layout/fragment_patient_record_add_medical_history.xml
Medical History | adding missing checkboxes
=> Item high prio mia

.idea/kotlinScripting.xml, app/build.gradle.kts, app/src/main/java/com/triadss/doctrack2/repoositories/WearableDeviceRepository.java
_**In the WearableDeviceRepository.java**_
~ implemented wearable device repository functions (ADD, GET, GETALL,  UPDATE, and DELETE).
~ implemented also their callbacks.
~ not yet tested, but in theory, it will work i tthink.
=> Item_HighjPrio_Nico - Wearable Device Repository

app/src/main/java/com/triadss/doctrack2/activity/LoginActivity.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/HealthProfessionalPending.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/HealthProfessionalUpcoming.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/AddMedicalHistory.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/AddMedication.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/AddPatientFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/AddVitalSigns.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfHomeFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalReportAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfessionalReportFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/UpdateMedicalHistory.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/UpdateMedications.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/UpdatePersonalInfo.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/UpdateVitalSigns.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientReportAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientReportFragment.java, app/src/main/java/com/triadss/doctrack2/config/constants/AppointmentTypeConstants.java, app/src/main/java/com/triadss/doctrack2/config/constants/SessionConstants.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/MedicalHistoryRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/MedicationRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/ReportsRepository.java, app/src/main/res/layout/list_reports.xml, app/src/main/res/menu/bottom_nav_menu.xml
Added Reports page for Health Professional
Registers the following to Reports:
1. Appointment Accept/Reject
2. Appointment Cancel/Reschedule
3. Create Patient Personal Info, Medical History, Vital Signs
4. Add/Remove Patient Medications
5. Updated Patient Personal Info, Medical History, Vital Signs
=> Completed Health Professional Reports

app/build.gradle.kts, app/src/main/java/com/triadss/doctrack2/activity/core/DeviceFragment.java, app/src/main/java/com/triadss/doctrack2/dto/WearableDeviceDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/VitalSignsRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/WearableDeviceRepository.java, app/src/main/res/layout/fragment_device_with_device.xml
**_IMPLEMENTED_**
~ implement auto gone/visible device registered table when there is no/a wearables nearby and paired
~ implemented auto registered device if not registered in the database
~ added ownerId and isNearby in the WearableDeviceRepository
~ fetch device registered and displays the table if searched
~ added additional labels in the device registered
~ can now fetch patient's vital signs data
~ added toast message indicator in sync device button and etc
~ cleaned up and refactored some lines of codes
~ denying in syncing device if not paired or no nearby wearable device found.
~ improved the UI
~ will reveal "No Device Found" if there's no device paired or nearby
~ already tested by me
**_NOT YET IMPLEMENTED_**
~ get /received the data (heart rate and device sync date) from the …
=> Item_HighPrio_Nico - Core: Device Sync I

app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragment/HealthProfHomeFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientHomeAppointmentAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientHomeFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragment/PatientHomeMedicationAdapter.java, app/src/main/res/layout/fragment_health_prof_home_page.xml, app/src/main/res/layout/fragment_patient_home_page.xml
Health Prof Home page:
Populated Appointments
Patient Home page:
Populated Appointments
Populated Medications
=> Health Prof and Patient Home Page Data Population

app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/AddMedicationAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentUpcomingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/medications/AddMedication.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/medications/UpdateMedications.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/patient/AddPatientFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/records/AddMedicalHistory.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/records/UpdateMedicalHistory.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/records/UpdatePersonalInfo.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/vitalsigns/AddVitalSigns.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/vitalsigns/UpdateVitalSigns.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientMedicationOngoingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/medications/PatientMedicationAddFragment.java
~ fix ButtonManager importing issues.
~ fix AlertDialog getting the button issue.
=> Item_High_Prio_Nico - ButtonManager Importing Issue

app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientMedicationFragmentPageAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientMedicationOngoingAdapter.java, app/src/main/res/layout/dialog_update_medication.xml, app/src/main/res/layout/fragment_patient_medication.xml
Remove Note and Name in Medication Update Dialog
Added Date and Time
Added Date and Time validation
Update button updates medication Date and Time
=> Updated Medication Update Dialog

app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/patient/AddPatientFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/records/UpdatePersonalInfo.java, app/src/main/res/layout/fragment_patient_record_add_patient.xml, app/src/main/res/layout/fragment_update_record.xml, app/src/main/res/values/address.xml, app/src/main/res/values/civil_status.xml, app/src/main/res/values/course.xml, app/src/main/res/values/gender.xml, app/src/main/res/values/year.xml
Updated the Following:
1. Gender is now dropdown
2. Course is now dropdown
3. Address has autocomplete
4. Civil Status is now dropdown
5. Year is now dropdown
=> Patient Info Field  Update

app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/reports/HealthProfessionalReportFragment.java, app/src/main/res/layout/fragment_healthprof_reports_list.xml
~ Added "All" toggle button UI
~ Will fetch all kinds of reports in the reports list.
~ Made it checked == true as its default values when viewing report
=> Item_HighPrio_Nico - All Toggle in the Health Prof's Reports

app/src/main/AndroidManifest.xml, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/PatientHomeFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentPending.java, app/src/main/java/com/triadss/doctrack2/config/constants/NotificationConstants.java, app/src/main/java/com/triadss/doctrack2/config/model/MedicationModel.java, app/src/main/java/com/triadss/doctrack2/dto/DateTimeDto.java, app/src/main/java/com/triadss/doctrack2/notification/NotificationBackgroundWorker.java, app/src/main/java/com/triadss/doctrack2/notification/NotificationMedicationScheduleWorker.java, app/src/main/java/com/triadss/doctrack2/repoositories/MedicationRepository.java
Ongoing Medication will be notified when past timestamp
=> Added Medication Notification

app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/dto/DateDto.java
~ Added isDayWeekend() where it will return true if the day is weekend or not
~ Will unable to set appointment if the scheduled day is weekend
~ Will show toast message "Appointments cannot be scheduled on Weekends"
~ Updated invalid time toast message to "Must be between 8:00 - 17:00"
=> Item_High_Prio_Nico - Unable to Set Appointments on Weekends

app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/reports/HealthProfessionalReportFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/records/PatientReportFragment.java, app/src/main/res/layout/fragment_healthprof_reports_list.xml, app/src/main/res/layout/fragment_patient_reports_list.xml, app/src/main/res/layout/list_reports.xml
changed toggle to radio buttons and changed layout for cards
=> Updated UI Reports both HealthProf and Patient

app/src/main/java/com/triadss/doctrack2/activity/LoginActivity.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentUpcomingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalAppointmentFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalPending.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalStatus.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalUpcoming.java, app/src/main/java/com/triadss/doctrack2/activity/patient/PatientHome.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientAppointmentStatusAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientMedicationOngoingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/PatientHomeFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentPending.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentStatus.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/medications/PatientMedicationFragment.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/MedicationRepository.java, app/src/main/res/layout/fragment_patient_appointment_reschedule.xml
Updating Patient Medication updates notifications
Healthprof shows Completed status
Fixed appointment time picker doesn't crash
Fixed upcoming appointment time range
Code cleanup
Bug Fixes
=> Updates and Fixes

.idea/compiler.xml, .idea/gradle.xml, .idea/kotlinScripting.xml, .idea/misc.xml, app/src/main/java/com/triadss/doctrack2/activity/core/DeviceFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/dto/DateTimeDto.java, build.gradle.kts
**_Can't select Day before Today in the Appointment Request_**
~ can't select day before today in the Date Picker
~ tested Date and Time picker
**_Unable to Sync Vital Signs when there is currently in appointment (Pending)_**
~ added isToday() and isCurrentTimeRange() in DateTimeDto
~ isCurrentTimeInRange()  returns currentHour == appointmentHour || currentHour == (appointmentHour + 1)
~ added isCurrentInAnAppointment() and isValidSync()
~ will not sync if the there is no appointments of that patient that is current in an appointment
~ will not sync if there is no appointment made
~ when successfully send vital signs to smartwach, will show a toast message "Data sent successfully"
=> Item_HighPrio_Nico - Can't select Day before Today & Unable to Sync Vital Signs when there is no Appointment in CurrentDate

app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfHomeAppointmentAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentStatusAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentUpcomingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalUpcoming.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientHomeAppointmentAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientMedicationOngoingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentPending.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/config/constants/AppointmentTypeConstants.java, app/src/main/java/com/triadss/doctrack2/dto/DateTimeDto.java, app/src/main/java/com/triadss/doctrack2/dto/TimeDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java, app/src/main/res/layout/dialog_update_medication.xml, app/src/main/res/layout/fragment_health_prof_home_page_pending.xml, app/src/main/res/layout/fragment_patient_homepage_pending.xml
1. Fixed Appointment Reschedule Crash
2. Fixed Medication Update Crash
3. Added Rejected Appointment Status
4. Appointment status will be set to Rejected instead of being deleted
5. Disabled previous dates for Appointment Date Pickers
6. Fixed Date Range being the same in Appointments
7. Home Page shows Appointments in Date Range
=> QA Fixes + Rejected Status

app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentUpcomingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/HealthProfHomeFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalPending.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalStatus.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalUpcoming.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/PatientHomeFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentPending.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentStatus.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java, app/src/main/res/layout/fragment_health_prof_home_page.xml, app/src/main/res/layout/fragment_health_prof_home_page_pending.xml, app/src/main/res/layout/fragment_health_professional_pending.xml, app/src/main/res/layout/fragment_health_professional_status.xml, app/src/main/res/layout/fragment_health_professional_upcoming.xml, app/src/main/res/layout/fragment_patient_appointment_pending.xml, app/src/main/res/layout/fragment_patient_appointment_status.xml, app/src/main/res/layout/fragment_patient_home_page.xml, app/src/main/res/values/strings.xml
Added Filter for all appointment pages
- Patient Pending
- Patient Status
- HealthProf Upcoming
- HealthProf Pending
- HealthProf Status
Clarified labels on homepage regarding Total Appointments and top 5 appointments
Removed time in Appointment Upcoming birthday
=> Appointment Filters + QoL Updates

app/src/main/java/com/triadss/doctrack2/activity/patient/PatientHome.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/PatientHomeFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/medications/PatientMedicationOngoingFragment.java, app/src/main/java/com/triadss/doctrack2/config/constants/DocTrackConstant.java, app/src/main/java/com/triadss/doctrack2/notification/NotificationMedicationScheduleWorker.java, app/src/main/java/com/triadss/doctrack2/repoositories/MedicationRepository.java
Fixed Medication Notification
Code fixes
=> Medication Notif fix

app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/config/constants/ErrorMessageConstants.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java
Patient Appointment DatePicker Weekend validation is now on select
=> Appointment DatePicker QoL

app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/config/constants/FireStoreCollection.java, app/src/main/java/com/triadss/doctrack2/dto/DateDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/ConstantRepository.java
**_FireStoreCollection.java_**
~ added CONSTANT_TABLE 
**_ConstantRepository..java_**
~implemented getHolidays()
**_PatientAppointmentRequest.java_**
~ unable to select a date that is holiday
~ will show a message that the date picked is a holiday, if not then the user can select in the date picker
=> Item_HighPrio_Nico - Unable to Set Appointment During Holidays

app/src/main/java/com/triadss/doctrack2/activity/healthprof/adapters/HealthProfessionalAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/appointments/HealthProfessionalPending.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientAppointmentPendingAdapter.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentPending.java, app/src/main/java/com/triadss/doctrack2/activity/patient/fragments/appointments/PatientAppointmentRequest.java, app/src/main/java/com/triadss/doctrack2/dto/DateDto.java, app/src/main/java/com/triadss/doctrack2/utils/AppointmentFunctions.java, app/src/main/res/layout/activity_login.xml
Fixed Holiday Checker
Applied Holiday Checker for Rescheduling appointments
=> Holiday Checker QoL

app/src/main/java/com/triadss/doctrack2/activity/core/DeviceFragment.java, app/src/main/java/com/triadss/doctrack2/activity/patient/adapters/PatientMedicationOngoingAdapter.java, app/src/main/java/com/triadss/doctrack2/dto/DateTimeDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/AppointmentRepository.java
~ Fixed Filter to use End Date of Appointment
~ Able to send data to the smartwatch during appointment time schedule range
~ Tested using mobile and smartwatch physical devices.
=> Item_HighPrio_Nico - Able to Sync Data to the Mobile during Appointment

app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/medications/AddMedication.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/patient/AddPatientFragment.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/records/AddMedicalHistory.java, app/src/main/java/com/triadss/doctrack2/activity/healthprof/fragments/vitalsigns/AddVitalSigns.java, app/src/main/java/com/triadss/doctrack2/dto/AddPatientDto.java, app/src/main/java/com/triadss/doctrack2/repoositories/MedicalHistoryRepository.java, app/src/main/java/com/triadss/doctrack2/repoositories/VitalSignsRepository.java
=> Added default for Med History and Vital Signs  

app/src/main/AndroidManifest.xml, app/src/main/res/layout/list_appointment_upcoming.xml
Purpose will now be Wrapped and anything else will adjust below
Login Page will now have black status bar
=> Upcoming Appointments Wrapping Fix + Login Page Status Bar Fix
